### ISSUE TITLE
Latest Docker GPU image fails to run README script

### ISSUE THREAD

**Issue by alexkreidler** [deepdoctection/deepdoctection#190]
**Bug** 💥
I built the `pytorch-gpu` Docker image (which took 21 minutes) and then tried to run the [example script in the README](https://github.com/deepdoctection/deepdoctection/tree/master#inference).
```
root@e6d473008883:/data# python3 dd.py 
Traceback (most recent call last):
  File "dd.py", line 2, in <module>
    import deepdoctection as dd
  File "/usr/local/lib/python3.8/dist-packages/deepdoctection/__init__.py", line 14, in <module>
    from .utils.file_utils import _LazyModule, get_tf_version, pytorch_available, tf_available
  File "/usr/local/lib/python3.8/dist-packages/deepdoctection/utils/__init__.py", line 9, in <module>
    from .context import *
  File "/usr/local/lib/python3.8/dist-packages/deepdoctection/utils/context.py", line 32, in <module>
    from cv2 import imwrite
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
```

**Expected behavior**  🧮 
The script should run properly.

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 20.04.6 LTS

**Comment by jonahkaye** [comment]
@alexkreidler has this been resolved?
