### ISSUE TITLE
Error in setting newspaper model

### ISSUE THREAD

**Issue by szekrenyesi** [deepdoctection/deepdoctection#284]
Hi, when I try to initialize the Newspaper extension, I got this error:

page_parser = dd.PageParsingService(text_container = dd.LayoutType.word, floating_text_block_categories=[layout_item for layout_item in NewspaperExtension])
TypeError: __init__() got an unexpected keyword argument 'floating_text_block_categories'

**Comment by JaMe76** [comment]
Hi, may I ask what deepdoctection version you are using?

The 

```python

import deepdoctection as dd

print(dd.__version__)
```

`PageParsingService` arguments haven't changed for a long time.

**Comment by JaMe76** [comment]
That’s the problem.

lease upgrade to the latest release, e.g. 0.29

**Comment by szekrenyesi** [comment]
Thanks! yes, the upgrade helped. However, now I have another issue. Could you help which version of Pillow (or other fix) needed to resolve?

Traceback (most recent call last):
  File "test_new.py", line 27, in <module>
    dd.ModelCatalog.register("layoutparser/newspaper/model_final.pth",dd.ModelProfile(
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/deepdoctection/utils/file_utils.py", line 693, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/deepdoctection/utils/file_utils.py", line 703, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/deepdoctection/extern/__init__.py", line 28, in <module>
    from .hflayoutlm import *
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/deepdoctection/extern/hflayoutlm.py", line 56, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1355, in __getattr__
    value = getattr(module, name)
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/aramis/Environments/layout/deepdocdetection/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.layoutlmv2.modeling_layoutlmv2 because of the following error (look up to see its traceback):
**module 'PIL.Image' has no attribute 'LINEAR'**

**Comment by szekrenyesi** [comment]
If I downgrade to Pillow==9.5 Then I got this: 

ImportError: cannot import name 'convert_to_tensor' from 'tensorflow' (unknown location)

**Comment by muruguru** [comment]
I see the same issue with 0.30 version

**Comment by JaMe76** [comment]
Closing with https://github.com/deepdoctection/deepdoctection/pull/310.
