### ISSUE TITLE
AttributeError: module 'deepdoctection.extern' has no attribute 'D2FrcnnDetector'

### ISSUE THREAD

**Issue by szekrenyesi** [deepdoctection/deepdoctection#285]
Hi, I tried to set NewsPaperExtension following the guide here: https://deepdoctection.readthedocs.io/en/latest/tutorials/running_pre_trained_models_from_third_party_libraries_notebook/

But got this error: 

Traceback (most recent call last):
  File "test_new.py", line 47, in <module>
    d2_detector = dd.D2FrcnnDetector(path_config,path_weights,categories,config_overwrite=["NMS_THRESH_CLASS_AGNOSTIC=0.8","MODEL.ROI_HEADS.SCORE_THRESH_TEST=0.1"])
  File "/data/aramis/Environments/layout/deepdoctection/lib/python3.8/site-packages/deepdoctection/utils/file_utils.py", line 694, in __getattr__
    value = getattr(module, name)
AttributeError: module 'deepdoctection.extern' has no attribute 'D2FrcnnDetector'

Deepdoctection version: 0.29

**Comment by JaMe76** [comment]
Did you install Detectron2 ? 

There are some installation option where Detectron2 must be installed separately.

**Comment by AbhayMishraVK** [comment]
Hey you got how to tackle this error ?? I am getting the same error.

**Comment by afriedman412** [comment]
had the same problem, got it working with a fresh environment

here's the requirements.txt i used...
```torch==2.2.1
torchvision
python-doctr
deepdoctection
pdfplumber
autopep8
isort
ipykernel
pango```

**Comment by samuel-s-marques** [comment]
Same problem. And, yes, I do have detectron2 installed.

**Comment by samuel-s-marques** [comment]
Ok, that's on me. The error happened because I didn't install `detectron2`. 😑 sorry
