### ISSUE TITLE
Table Transformer model is not being loaded with document analyzer

### ISSUE THREAD

**Issue by TanvirKasir786** [deepdoctection/deepdoctection#295]
I have tried to load the table transformer detection and segmentation model in the doctection analyzer as indicated in the repo but I get the following error: 
Model not found in ModelCatalog. Make sure, you have places model weights in the cache dir
Traceback (most recent call last):
  File "/home/tkasir/Scripts/doctection_multipage.py", line 26, in <module>
    analyzer =dd.get_dd_analyzer(config_overwrite=
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 454, in get_dd_analyzer
    return build_analyzer(cfg)
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 269, in build_analyzer
    d_layout = build_detector(cfg, "LAYOUT")
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 142, in build_detector
    profile = ModelCatalog.get_profile(weights)
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/extern/model.py", line 829, in get_profile
    raise KeyError("Model Profile does not exist. Please make sure the model is registered")
KeyError: 'Model Profile does not exist. Please make sure the model is registered'

Although when I check the model registry and the file, both model weight exists and the model is visible in the registry. Here is the model catalog printed: 

['layout/model-800000_inf_only.data-00000-of-00001', 'cell/model-1800000_inf_only.data-00000-of-00001', 'item/model-1620000_inf_only.data-00000-of-00001', 'item/model-1620000.data-00000-of-00001', 'layout/model-800000.data-00000-of-00001', 'cell/model-1800000.data-00000-of-00001', 'layout/d2_model-800000-layout.pkl', 'layout/d2_model_0829999_layout_inf_only.pt', 'layout/d2_model_0829999_layout.pth', 'layout/d2_model_0829999_layout_inf_only.ts', 'cell/d2_model-1800000-cell.pkl', 'cell/d2_model_1849999_cell_inf_only.pt', 'cell/d2_model_1849999_cell_inf_only.ts', 'cell/d2_model_1849999_cell.pth', 'item/d2_model-1620000-item.pkl', 'item/d2_model_1639999_item.pth', 'item/d2_model_1639999_item_inf_only.pt', 'item/d2_model_1639999_item_inf_only.ts', 'microsoft/layoutlm-base-uncased/pytorch_model.bin', 'microsoft/layoutlm-large-uncased/pytorch_model.bin', 'microsoft/layoutlmv2-base-uncased/pytorch_model.bin', 'microsoft/layoutxlm-base/pytorch_model.bin', 'microsoft/layoutlmv3-base/pytorch_model.bin', 'microsoft/table-transformer-detection/pytorch_model.bin', 'microsoft/table-transformer-structure-recognition/pytorch_model.bin', 'doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt', 'doctr/db_resnet50/tf/db_resnet50-adcafc63.zip', 'doctr/crnn_vgg16_bn/pt/crnn_vgg16_bn-9762b0b0.pt', 'doctr/crnn_vgg16_bn/tf/crnn_vgg16_bn-76b7f2c6.zip', 'fasttext/lid.176.bin', 'layoutparser/tablebank_1/model_final.pth']

I have the latest version of doctection installed and transformer version 4.37.0

Here is the code when trying to initialize the analyzer with table transformer model weights:
analyzer =dd.get_dd_analyzer(config_overwrite=
   ["PT.LAYOUT.WEIGHTS= microsoft/table-transformer-detection/pytorch_model.bin",
    "PT.ITEM.WEIGHTS=microsoft/table-transformer-structure-recognition/pytorch_model.bin",
    "PT.ITEM.FILTER=['table']",
    "OCR.USE_DOCTR=True",
    "OCR.USE_TESSERACT=False",
    "TEXT_ORDERING.INCLUDE_RESIDUAL_TEXT_CONTAINER=True",
    "TEXT_ORDERING.PARAGRAPH_BREAK=0.01",
                        ])

**Comment by JaMe76** [comment]
Do you have a space between = and the model name in your code?

`
"PT.LAYOUT.WEIGHTS= microsoft/table-transformer-detection/pytorch_model.bin"
`

If so, the the code is looking for `" microsoft/table-transformer-detection/pytorch_model.bin"` in the model catalog but won't be able to find the profile.

**Comment by TanvirKasir786** [comment]
I did indeed have a space between, which when rectified yields another error: 

You are using a model of type table-transformer to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/tkasir/.cache/deepdoctection/weights/microsoft/table-transformer-detection/pytorch_model.bin'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tkasir/Scripts/doctection_multipage.py", line 26, in <module>
    analyzer =dd.get_dd_analyzer(config_overwrite=
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 454, in get_dd_analyzer
    return build_analyzer(cfg)
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 269, in build_analyzer
    d_layout = build_detector(cfg, "LAYOUT")
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py", line 155, in build_detector
    return HFDetrDerivedDetector(
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/extern/hfdetr.py", line 150, in __init__
    self.hf_detr_predictor = self.set_model(path_weights)
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/deepdoctection/extern/hfdetr.py", line 180, in set_model
    return TableTransformerForObjectDetection.from_pretrained(
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2950, in from_pretrained
    _adapter_model_path = find_adapter_config_file(
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/transformers/utils/peft_utils.py", line 87, in find_adapter_config_file
    adapter_cached_filename = cached_file(
  File "/home/tkasir/anaconda3/envs/izwe/lib/python3.9/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/home/tkasir/.cache/deepdoctection/weights/microsoft/table-transformer-detection/pytorch_model.bin'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by JaMe76** [comment]
I am not able to reproduce the error. Did you change the default .yaml configuration? It seems that you changed the config pointing to a model with no valid HF repository. 

Can you provide more information about your configuration ?
