### ISSUE TITLE
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:

### ISSUE THREAD

**Issue by ZHUGUODONG1** [deepdoctection/deepdoctection#299]
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

Traceback (most recent call last):
  File "doctest.py", line 6, in <module>
    analyzer = dd.get_dd_analyzer()  # instantiate the built-in analyzer similar to the Hugging Face space demo
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/utils/file_utils.py", line 715, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/utils/file_utils.py", line 725, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/analyzer/__init__.py", line 22, in <module>
    from .dd import *
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/analyzer/dd.py", line 32, in <module>
    from ..extern.base import ObjectDetector
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/extern/__init__.py", line 25, in <module>
    from .doctrocr import *
  File "/usr/local/lib/python3.8/site-packages/deepdoctection/extern/doctrocr.py", line 43, in <module>
    from doctr.models.detection.predictor import DetectionPredictor  # pylint: disable=W0611
  File "/usr/local/lib/python3.8/site-packages/doctr/__init__.py", line 1, in <module>
    from . import io, models, datasets, transforms, utils
  File "/usr/local/lib/python3.8/site-packages/doctr/io/__init__.py", line 2, in <module>
    from .html import *
  File "/usr/local/lib/python3.8/site-packages/doctr/io/html.py", line 8, in <module>
    from weasyprint import HTML
  File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/usr/local/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/usr/local/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 428, in <module>
    gobject = _dlopen(
  File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by WYBupup** [comment]
same problem. Have you solved it?
