### ISSUE TITLE
AttributeError: WEIGHTS_TS

### ISSUE THREAD

**Issue by phuchm** [deepdoctection/deepdoctection#301]
**Bug** 💥
When I run Inference with deepdoctection-0.30 from exactly code in README, I got error message as below:
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    analyzer = dd.get_dd_analyzer()  # instantiate the built-in analyzer similar to the Hugging Face space demo
  File "deepdoctection/analyzer/dd.py", line 458, in get_dd_analyzer
    return build_analyzer(cfg)
  File "deepdoctection/analyzer/dd.py", line 273, in build_analyzer
    d_layout = build_detector(cfg, "LAYOUT")
  File "deepdoctection/analyzer/dd.py", line 135, in build_detector
    else (getattr(cfg.PT, mode).WEIGHTS if detectron2_available() else getattr(cfg.PT, mode).WEIGHTS_TS)
  File "deepdoctection/utils/metacfg.py", line 46, in __getattr__
    raise AttributeError(name)
AttributeError: WEIGHTS_TS

**Comment by JaMe76** [comment]
It looks that the `.yaml` file that is used to configure the analyzer does not align with the deepdoctection version.

Maybe forcing to reset the config file helps:

```python
analyzer = dd.get_dd_analyzer(reset_config_file=True)
```
