### ISSUE TITLE
[Error] Can't load tokenizer form layoutlm 

### ISSUE THREAD

**Issue by yumikim381** [deepdoctection/deepdoctection#321]
**Bug** 💥
I m getting this issue when i try to load the analyzer 

Traceback (most recent call last):
  File "testing.py", line 133, in <module>
    analyzer = dd.get_dd_analyzer()
  File "/myhome/deepdoctection/deepdoctection/utils/file_utils.py", line 704, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/myhome/deepdoctection/deepdoctection/utils/file_utils.py", line 714, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myhome/deepdoctection/deepdoctection/analyzer/__init__.py", line 22, in <module>
    from .dd import *
  File "/myhome/deepdoctection/deepdoctection/analyzer/dd.py", line 38, in <module>
    from ..pipe.base import PipelineComponent
  File "/myhome/deepdoctection/deepdoctection/pipe/__init__.py", line 31, in <module>
    from .lm import *
  File "/myhome/deepdoctection/deepdoctection/pipe/lm.py", line 39, in <module>
    ("LayoutLMForTokenClassification", False): LayoutLMTokenizerFast.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2070, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'microsoft/layoutlm-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'microsoft/layoutlm-base-uncased' is the correct path to a directory containing all relevant files for a LayoutLMTokenizerFast tokenizer.

**Expected behavior**  🧮 
Describe what you would have expected

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
I think, you are running on an older version. 
The issue results from the fact that it tries to download some tokenizer information (which has nothing to do for running the analyzer) and fails because the Huggingface hub was down until a few minutes ago. 

Try to install the most recent version (i.e. v.0.31.0) or re-run the code once the Huggingface hub is up again.
