### ISSUE TITLE
Error in loading TATR-v1.1-all

### ISSUE THREAD

**Issue by michaeldlanier2** [deepdoctection/deepdoctection#359]
The following code causes an AttributeError when loading the [microsoft/table-transformer-structure-recognition-v1.1-all](https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-all) model in Python 3.10.14 on Ubuntu 22.04 using the current version of deepdoctection[pt].
```
import torch
import huggingface_hub as hf_hub
import deepdoctection as dd
import safetensors.torch

hf_hub.hf_hub_download(
    repo_id="microsoft/table-transformer-structure-recognition-v1.1-all",
    filename="model.safetensors",
    local_dir="/root/.cache/deepdoctection/weights/microsoft/table-transformer-structure-recognition-v1.1-all",
    force_download=True
)
for filename in ["config.json", "preprocessor_config.json"]:
    hf_hub.hf_hub_download(
        repo_id="microsoft/table-transformer-structure-recognition-v1.1-all",
        filename=filename,
        local_dir="/root/.cache/deepdoctection/configs/microsoft/table-transformer-structure-recognition-v1.1-all",
        force_download=True
    )

pt_state_dict = safetensors.torch.load_file("/root/.cache/deepdoctection/weights/microsoft/table-transformer-structure-recognition-v1.1-all/model.safetensors")
torch.save(pt_state_dict, "/root/.cache/deepdoctection/weights/microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin")

dd.ModelCatalog.register(
    "microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin",
    dd.ModelProfile(
        name="microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin",
        description="Table Transformer (TATR) model trained on PubTables1M and FinTabNet.c. "
        "It was introduced in 'Aligning benchmark datasets for table structure recognition' "
        "by Smock et al. (2023). This model is able to recognize the structure of tables",
        size=[],
        tp_model=False,
        config="microsoft/table-transformer-structure-recognition-v1.1-all/config.json",
        preprocessor_config="microsoft/table-transformer-structure-recognition-v1.1-all/preprocessor_config.json",
        categories={
            1: dd.LayoutType.TABLE,
            2: dd.LayoutType.COLUMN,
            3: dd.LayoutType.ROW,
            4: dd.CellType.COLUMN_HEADER,
            5: dd.CellType.PROJECTED_ROW_HEADER,
            6: dd.CellType.SPANNING,
        },
        dl_library="PT",
        model_wrapper="HFDetrDerivedDetector",
    )
)

path_weights = dd.ModelCatalog.get_full_path_weights("microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin")
path_config = dd.ModelCatalog.get_full_path_configs("microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin")
path_feature_extractor_config = dd.ModelCatalog.get_full_path_preprocessor_configs("microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin")

categories = dd.ModelCatalog.get_profile("microsoft/table-transformer-structure-recognition-v1.1-all/pytorch_model.bin").categories
d_layout = dd.HFDetrDerivedDetector(
    path_config_json=path_config,
    path_weights=path_weights,
    path_feature_extractor_config_json=path_feature_extractor_config,
    categories=categories
)
```

**Bug** 💥
```
[0816 14:12.33 @file_utils.py:36]  INF  PyTorch version 2.4.0 available.
[0816 14:12.33 @file_utils.py:74]  INF  Disabling Tensorflow because USE_TORCH is set
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 115M/115M [00:03<00:00, 29.2MB/s]
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 76.8k/76.8k [00:00<00:00, 2.21MB/s]
preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 374/374 [00:00<00:00, 3.02MB/s]
You are using a model of type table-transformer to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/data/workspace/error_rep.py", line 52, in <module>
    d_layout = dd.HFDetrDerivedDetector(
  File "/data/workspace/.conda/lib/python3.10/site-packages/deepdoctection/extern/hfdetr.py", line 196, in __init__
    self.hf_detr_predictor = self.get_model(self.path_weights, self.config)
  File "/data/workspace/.conda/lib/python3.10/site-packages/deepdoctection/extern/hfdetr.py", line 222, in get_model
    return TableTransformerForObjectDetection.from_pretrained(
  File "/data/workspace/.conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3810, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/data/workspace/.conda/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 1302, in __init__
    self.model = TableTransformerModel(config)
  File "/data/workspace/.conda/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 1133, in __init__
    backbone = TableTransformerConvEncoder(config)
  File "/data/workspace/.conda/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 289, in __init__
    backbone = create_model(
  File "/data/workspace/.conda/lib/python3.10/site-packages/timm/models/_factory.py", line 97, in create_model
    model_source, model_name = parse_model_name(model_name)
  File "/data/workspace/.conda/lib/python3.10/site-packages/timm/models/_factory.py", line 16, in parse_model_name
    if model_name.startswith('hf_hub'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
**Expected behavior**  🧮 
The HFDetrDerivedDetector loads the model.

**Comment by JaMe76** [comment]
This is just following the Traceback and I am not sure if this takes you further but it seems there is an issue with the config:

The first version of Tatr has:

https://huggingface.co/microsoft/table-transformer-structure-recognition/blob/f4d4bdc85c3fe4b1fa49658882a5d38bbdd0f343/config.json#L9

whereas your config states:
https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-all/blob/7587a7ef111d9dcbf8ac695f1376ab7014340a0c/config.json#L9

The null Value is responsible for  the AttributeError.

**Comment by michaeldlanier2** [comment]
That's odd. This code works
```
from transformers import TableTransformerForObjectDetection
model = TableTransformerForObjectDetection.from_pretrained("microsoft/table-transformer-structure-recognition-v1.1-all")
```
but this errors out.
```
from transformers import TableTransformerForObjectDetection, PretrainedConfig

config = PretrainedConfig.from_pretrained("microsoft/table-transformer-structure-recognition-v1.1-all")
model = TableTransformerForObjectDetection.from_pretrained("microsoft/table-transformer-structure-recognition-v1.1-all", config=config)
```
```
Traceback (most recent call last):
  File "/data/workspace/rag/error_rep copy.py", line 9, in <module>
    model = TableTransformerForObjectDetection.from_pretrained("microsoft/table-transformer-structure-recognition-v1.1-all", config=config)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 1372, in __init__
    self.model = TableTransformerModel(config)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 1203, in __init__
    backbone = TableTransformerConvEncoder(config)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/table_transformer/modeling_table_transformer.py", line 293, in __init__
    backbone = AutoBackbone.from_config(config.backbone_config)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 423, in from_config
    trust_remote_code, config._name_or_path, has_local_code, has_remote_code
AttributeError: 'dict' object has no attribute '_name_or_path'
```
The issue seems to be with how the config is built.

**Comment by michaeldlanier2** [comment]
I was able to get around that error by downloading the config files to the same directory as the model weights and changing HFDetrDerivedDetector.get_model to not pass the config, which causes the model to load with the config in the same directory. However, trying to use the pipeline for analysis causes an additional error.
```
  File "/data/workspace/rag/extract.py", line 371, in process_pdf
    for page_number, page in enumerate(df):
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/dataflow/common.py", line 109, in __iter__
    for dp in self.df:
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/dataflow/common.py", line 109, in __iter__
    for dp in self.df:
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/dataflow/common.py", line 109, in __iter__
    for dp in self.df:
  [Previous line repeated 3 more times]
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/dataflow/common.py", line 110, in __iter__
    ret = self.func(copy(dp))  # shallow copy the list
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/pipe/base.py", line 106, in pass_datapoint
    self.serve(dp)
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/pipe/sub_layout.py", line 196, in serve
    detect_result_list = self.predictor.predict(np_image)
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/extern/hfdetr.py", line 203, in predict
    results = detr_predict_image(
  File "/opt/home/rag/lib/python3.10/site-packages/deepdoctection/extern/hfdetr.py", line 77, in detr_predict_image
    inputs = feature_extractor(images=np_img, return_tensors="pt")
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 549, in __call__
    return self.preprocess(images, **kwargs)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/detr/image_processing_detr.py", line 1284, in preprocess
    images = [
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/detr/image_processing_detr.py", line 1285, in <listcomp>
    self.resize(image, size=size, resample=resample, input_data_format=input_data_format)
  File "/opt/home/rag/lib/python3.10/site-packages/transformers/models/detr/image_processing_detr.py", line 937, in resize
    raise ValueError(
ValueError: Size must contain 'height' and 'width' keys or 'shortest_edge' and 'longest_edge' keys. Got dict_keys(['longest_edge']).
```

**Comment by michaeldlanier2** [comment]
That works perfectly. Thank you.
